### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by plehegar** [w3c/i18n-activity#847] opened 2020-02-14 22:22 UTC
**This is a tracker issue.** Only discuss things here if they are i18n group internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/manifest/issues/848

**Comment by xfq** [comment] 2022-06-01 01:05
WG issue closed as a duplicate of https://github.com/w3c/manifest/issues/676 (our tracker issue is https://github.com/w3c/i18n-activity/issues/914 )

**Closed as completed** 2023-12-28 16:03 UTC
Labels: duplicate, close?, tracker, s:appmanifest, wg:webapps
