### ISSUE TITLE
language tags in Verifiable Credentials Data Model 1.0

### ISSUE THREAD

**Issue by stpeter** [w3c/i18n-activity#600] opened 2018-10-04 17:08 UTC
Verifiable Credentials Data Model 1.0
https://w3c.github.io/vc-data-model/WD/2018-07-18/

The specification contains examples of fields for which it would be best to specify the language, such as:

> "name": "Jane Doe"

Other such examples are hinted at (e.g., various address fields). It is not clear from the specification if these examples, express or implied, are normative, or where the underlying ontologies are defined. In any case, there really must be a mechanism to specify the language of such fields, and there should be a mechanism to include multiple instances of the same field with different language tags (e.g., a name both in Latin script and in Japanese, as people often have on business cards and sometimes on official documents).

**Comment by aphillips** [comment] 2019-03-04 20:24
Marked as a duplicate of #580 during teleconference of 2019-02-28

**Closed as completed** 2019-03-07 10:40 UTC
Labels: duplicate, s:vc-data-model
