### ISSUE TITLE
[csswg-drafts] [css-logical] Flow-relative syntax for `margin`-like shorthands #1282

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#611] opened 2018-11-21 10:16 UTC
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/1282

**Comment by r12a** [comment] 2020-09-25 11:39
Closing this, since it's a duplicate of https://github.com/w3c/i18n-activity/issues/586

**Closed as completed by r12a** 2020-09-25 11:39 UTC
Labels: tracker, s:css-logical, wg:css
