### ISSUE TITLE
What do the writing-mode and direction properties do on view-transition pseudo-elements?

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#1625] opened 2022-12-01 14:55 UTC
8.3. [Setup view transition](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#setup-view-transition)

> Set capture’s [old styles](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#captured-element-old-styles) to the following:
> [...]
> * [writing-mode](https://www.w3.org/TR/css-writing-modes-4/#propdef-writing-mode)
> The [writing-mode](https://www.w3.org/TR/css-writing-modes-4/#propdef-writing-mode) of element.
> * [direction](https://www.w3.org/TR/css-writing-modes-3/#propdef-direction)
> The [direction](https://www.w3.org/TR/css-writing-modes-3/#propdef-direction) of element.

And similar in 8.9. [Update pseudo-element styles](https://www.w3.org/TR/2022/WD-css-view-transitions-1-20221124/#update-pseudo-element-styles).

These properties are set on elements that are images. But they don't have effect on images, do they? In other words, would anything change if these properties were omitted from the style for these view-transition pseudo-elements?

If they do have an effect, a note or an example could be useful.

---
**WHEN CREATING A NEW ISSUE DO SO ABOVE THIS PARAGRAPH, REPLACING THE PROMPTS, BUT LEAVE THIS PARAGRAPH INTACT AS WELL AS THE TEXT BELOW IT** When this issue is raised in the github/bugzilla/mail of the WG that owns the spec, use the text above this para as the basis for that comment. Then edit this issue to remove this paragraph and ALL THE TEXT ABOVE IT. Replace the text 'link_to_issue_raised' below with a link to the place you raised the issue, but leave the remaining text below this para unaltered.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ link_to_issue_raised

**Comment by xfq** [comment] 2023-03-31 05:38
Duplicate of https://github.com/w3c/i18n-activity/issues/1632

**Closed as completed** 2023-04-20 09:44 UTC
