### ISSUE TITLE
'deleteWordForwards' and 'deleteWordBackwards' not well defined

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#211] opened 2016-08-23 18:49 UTC
§ https://github.com/w3c/input-events/issues/72

**Comment by r12a** [comment] 2017-09-14 15:56
[Telecon] JcK: Add also that logical order should be used when talking about forwards and backwards.

**Comment by himorin** [comment] 2020-03-22 09:49
on this issue, WG is waiting for a suggestion from i18n on how to adjust the explanatory note text

**Comment by aphillips** [comment] 2022-03-07 23:44
This issue is waiting on a text suggestion by @r12a.

**Comment by xfq** [comment] 2024-11-22 01:36
Since @aphillips has confirmed in https://github.com/w3c/input-events/issues/72#issuecomment-2422709724 that it's OK, I think we can close this.

**Closed as completed by xfq** 2024-11-22 01:36 UTC
Labels: close?, s:input-events, needs-resolution, t:loc_input_x, wg:webediting
